const pieces = [
  {
    name: "Marshal",
    rank: "10",
    moves: 1,
    playerImage: "./images/Stratego_B10.svg.png",
    enemyImage: "./images/Stratego_R10.svg.png",
    quantity: 1,
  },
  {
    name: "General",
    rank: "9",
    moves: 1,
    playerImage: "./images/Stratego_B09.svg.png",
    enemyImage: "./images/Stratego_R09.svg.png",
    quantity: 1,
  },
  {
    name: "Colonel",
    rank: "8",
    moves: 1,
    playerImage: "./images/Stratego_B08.svg.png",
    enemyImage: "./images/Stratego_R08.svg.png",
    quantity: 2,
  },
  {
    name: "Major",
    rank: "7",
    moves: 1,
    playerImage: "./images/Stratego_B07.svg.png",
    enemyImage: "./images/Stratego_R07.svg.png",
    quantity: 3,
  },
  {
    name: "Captain",
    rank: "6",
    moves: 1,
    playerImage: "./images/Stratego_B06.svg.png",
    enemyImage: "./images/Stratego_R06.svg.png",
    quantity: 4,
  },
  {
    name: "Lieutenant",
    rank: "5",
    moves: 1,
    playerImage: "./images/Stratego_B05.svg.png",
    enemyImage: "./images/Stratego_R05.svg.png",
    quantity: 4,
  },
  {
    name: "Sergeant",
    rank: "4",
    moves: 1,
    playerImage: "./images/Stratego_B04.svg.png",
    enemyImage: "./images/Stratego_R04.svg.png",
    quantity: 4,
  },
  {
    name: "Miner",
    rank: "3",
    moves: 1,
    playerImage: "./images/Stratego_B03.svg.png",
    enemyImage: "./images/Stratego_R03.svg.png",
    quantity: 5,
  },
  {
    name: "Scout",
    rank: "2",
    moves: "3",
    playerImage: "./images/Stratego_B02.svg.png",
    enemyImage: "./images/Stratego_R02.svg.png",
    quantity: 8,
  },
  {
    name: "Spy",
    rank: "1",
    moves: 1,
    playerImage: "./images/Stratego_B01.svg.png",
    enemyImage: "./images/Stratego_R01.svg.png",
    quantity: 1,
  },
  {
    name: "Bomb",
    rank: "B",
    moves: 0,
    playerImage: "./images/Stratego_BB.svg.png",
    enemyImage: "./images/Stratego_RB.svg.png",
    quantity: 6,
  },
  {
    name: "Flag",
    rank: "F",
    moves: 0,
    playerImage: "./images/Stratego_BF.svg.png",
    enemyImage: "./images/Stratego_RF.svg.png",
    quantity: 1,
  },
];