const pieces = [
  {
    name: "Marshal",
    rank: "10",
    moves: 1,
    playerImage: "./images/Stratego_B10.svg.png",
    enemyImage: "./images/Stratego_R10.svg.png",
    quantity: 1,
  },
  {
    name: "General",
    rank: "9",
    moves: 1,
    playerImage: "./images/Stratego_B9.svg.png",
    enemyImage: "./images/Stratego_R9.svg.png",
    quantity: 1,
  },
  {
    name: "Colonel",
    rank: "8",
    moves: 1,
    playerImage: "./images/Stratego_B8.svg.png",
    enemyImage: "./images/Stratego_R8.svg.png",
    quantity: 2,
  },
  {
    name: "Major",
    rank: "7",
    moves: 1,
    playerImage: "./images/Stratego_B7.svg.png",
    enemyImage: "./images/Stratego_R7.svg.png",
    quantity: 3,
  },
  {
    name: "Captain",
    rank: "6",
    moves: 1,
    playerImage: "./images/Stratego_B6.svg.png",
    enemyImage: "./images/Stratego_R6.svg.png",
    quantity: 4,
  },
  {
    name: "Lieutenant",
    rank: "5",
    moves: 1,
    playerImage: "./images/Stratego_B5.svg.png",
    enemyImage: "./images/Stratego_R5.svg.png",
    quantity: 4,
  },
  {
    name: "Sergeant",
    rank: "4",
    moves: 1,
    playerImage: "./images/Stratego_B4.svg.png",
    enemyImage: "./images/Stratego_R4.svg.png",
    quantity: 4,
  },
  {
    name: "Miner",
    rank: "3",
    moves: 1,
    playerImage: "./images/Stratego_B3.svg.png",
    enemyImage: "./images/Stratego_R3.svg.png",
    quantity: 5,
  },
  {
    name: "Scout",
    rank: "2",
    moves: "3",
    playerImage: "./images/Stratego_B2.svg.png",
    enemyImage: "./images/Stratego_R2.svg.png",
    quantity: 8,
  },
  {
    name: "Spy",
    rank: "1",
    moves: 1,
    playerImage: "./images/Stratego_B1.svg.png",
    enemyImage: "./images/Stratego_R1.svg.png",
    quantity: 1,
  },
  {
    name: "Bomb",
    rank: "B",
    moves: 0,
    playerImage: "./images/Stratego_BB.svg.png",
    enemyImage: "./images/Stratego_RB.svg.png",
    quantity: 6,
  },
  {
    name: "Flag",
    rank: "F",
    moves: 0,
    playerImage: "./images/Stratego_BF.svg.png",
    enemyImage: "./images/Stratego_RF.svg.png",
    quantity: 1,
  },
];